sheets:
  - name: "Dynamic Report"
    sections:
      - id: "dynamic_products_section"
        title: "Dynamic Product List"
        type: "full"
        show_header: true
        locked: true # Section default lock
        columns:
          - field_name: "Name"
            header: "Product Name"
            width: 20
          - field_name: "MetaData"
            header: "Meta Data"
            width: 15
            locked: true # This should be inherited
          - field_name: "Price"
            header: "Price"
            width: 10
